### ISSUE TITLE
frosted crashes with non-ascii path

### ISSUE THREAD

**Issue by Shura1oplot** [timothycrosley/deprecated.frosted#10]
If file is being checked by frosted and it has path with non-ascii chars, frosted will crash:

```
Traceback (most recent call last):
  File "/home/shura/bin/frosted", line 20, in <module>
    from frosted import __version__, settings, reporter
  File "/home/shura/opt/linters/python2/frosted/lib/python2.7/site-packages/frosted-1.1.1-py2.7.egg/frosted/settings.py", line 47, in <module>
    potential_path = os.path.join(current_directory, ".editorconfig")
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 5: ordinal not in range(128)
```

If frosted runs in working dir with path with non-ascii chars, frosted will crash with the same exception.
It crashes only with python2.

**Comment by timothycrosley** [comment]
Thanks for catching this! It existed in one of my other utilities as well (isort), fixed with hotfix release 1.1.2
