### ISSUE TITLE
Not working on Python 3.4 at all for me

### ISSUE THREAD

**Issue by Ormod** [timothycrosley/deprecated.frosted#16]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/frosted", line 5, in <module>
    pkg_resources.run_script('frosted==1.1.2', 'frosted')
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources.py", line 487, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources.py", line 1337, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources.py", line 54, in execfile
    exec(compile(open(fn).read(), fn, 'exec'), globs, locs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/frosted-1.1.2-py3.4.egg/EGG-INFO/scripts/frosted", line 31, in <module>
    warnings = check_recursive(file_names, *_arguments)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/frosted-1.1.2-py3.4.egg/frosted/api.py", line 102, in check_recursive
    warnings += check_path(source_path, reporter, *_setting_overrides)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/frosted-1.1.2-py3.4.egg/frosted/api.py", line 83, in check_path
    return check(codestr, filename, reporter, *_setting_overrides)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/frosted-1.1.2-py3.4.egg/frosted/api.py", line 64, in check
    w = checker.Checker(tree, filename, None, *_active_settings)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/frosted-1.1.2-py3.4.egg/frosted/checker.py", line 260, in **init**
    self.handle_children(tree)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/frosted-1.1.2-py3.4.egg/frosted/checker.py", line 514, in handle_children
    self.handleNode(node, tree)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/frosted-1.1.2-py3.4.egg/frosted/checker.py", line 547, in handleNode
    handler(node)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/frosted-1.1.2-py3.4.egg/frosted/checker.py", line 821, in CLASSDEF
    self.handleNode(stmt, node)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/frosted-1.1.2-py3.4.egg/frosted/checker.py", line 547, in handleNode
    handler(node)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/frosted-1.1.2-py3.4.egg/frosted/checker.py", line 729, in FUNCTIONDEF
    self.LAMBDA(node)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/frosted-1.1.2-py3.4.egg/frosted/checker.py", line 756, in LAMBDA
    for annotation in (node.args.varargannotation,
AttributeError: 'arguments' object has no attribute 'varargannotation'

Same command line which was frosted -vb -r dir1 dir2 works when run from a frosted under Python 2.7.

**Comment by timothycrosley** [comment]
Thanks for reporting, will have a fix out for this soon!

**Comment by timothycrosley** [comment]
Fixed in release 1.2.0, thanks again for reporting!
