### ISSUE TITLE
UnicodeDecodeError with ä and ö in comment

### ISSUE THREAD

**Issue by hugovk** [timothycrosley/deprecated.frosted#56]
Frosted doesn't like the ä and ö in [this comment](https://github.com/python-pillow/Pillow/blob/master/PIL/WalImageFile.py#L78):

``` python
    # default palette taken from piffo 0.93 by Hans Häggström
```

For example:

```
C:\Temp>pip install -U frosted pyflakes
Requirement already up-to-date: frosted in c:\python27\lib\site-packages
Requirement already up-to-date: pyflakes in c:\python27\lib\site-packages
Cleaning up...

C:\Temp>wget https://raw.githubusercontent.com/python-pillow/Pillow/master/PIL/WalImageFile.py
--10:22:11--  https://raw.githubusercontent.com/python-pillow/Pillow/master/PIL/WalImageFile.py
           => `WalImageFile.py'
Resolving raw.githubusercontent.com... done.
Connecting to raw.githubusercontent.com[23.235.43.133]:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5,534 [text/plain]

100%[====================================>] 5,534          5.28M/s    ETA 00:00

10:22:11 (5.28 MB/s) - `WalImageFile.py' saved [5534/5534]


C:\Temp>pyflakes WalImageFile.py

C:\Temp>frosted WalImageFile.py
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\frosted.exe\__main__.py", line 9, in <module>
  File "C:\Python27\lib\site-packages\frosted\main.py", line 43, in main
    warnings += check_path(file_path, directly_being_checked=len(file_names), **arguments)
  File "C:\Python27\lib\site-packages\frosted\api.py", line 133, in check_path
    return check(codestr, filename, reporter, settings_path, **setting_overrides)
  File "C:\Python27\lib\site-packages\frosted\api.py", line 114, in check
    w = checker.Checker(tree, filename, None, ignore_lines=_noqa_lines(codeString), **active_settings)
  File "C:\Python27\lib\site-packages\frosted\api.py", line 40, in _noqa_lines
    g = tokenize.generate_tokens(StringIO(str(codeString)).readline)   # tokenize the string
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 1939: invalid continuation byte

C:\Temp>
```

After deleting the ä and ö from the file:

```
C:\Temp>frosted WalImageFile.py

C:\Temp>
```

This also causes [a problem](https://github.com/landscapeio/landscape-issues/issues/70) with [Landscape reporting the Pillow project has no warnings](landscape.io/github/hugovk/Pillow/landscape) when really it has plenty.

**Comment by carlio** [comment]
I added some more information about this as part of #53: https://github.com/timothycrosley/frosted/issues/53#issuecomment-55495303

Essentially it doesn't like the implicit conversion from `unicode` to `str` done when concatenating the error message information.
